/*传奇3 mysql 建库语句*/
CREATE TABLE TBL_ACCOUNT
(
	FLD_LOGINID		CHAR(10)		NOT NULL,		
	FLD_PASSWORD		CHAR(10)		NOT NULL,		
	FLD_USERNAME		CHAR(20)		NOT NULL,		

	FLD_CERTIFICATION	INT			DEFAULT 0
);

CREATE TABLE TBL_ACCOUNTADD
(
	FLD_LOGINID		CHAR(10)		NOT NULL,		
	FLD_SSNO		CHAR(14)		NOT NULL,		
	FLD_BIRTHDAY		CHAR(10)		NOT NULL,
	FLD_PHONE		CHAR(14)		NOT NULL,
	FLD_MOBILEPHONE		CHAR(13)		NOT NULL,
	FLD_ADDRESS1		VARCHAR(20)		NULL,
	FLD_ADDRESS2		VARCHAR(20)		NULL,
	FLD_EMAIL		VARCHAR(40)		NULL,
	FLD_QUIZ1		VARCHAR(20)		NULL,
	FLD_ANSWER1		VARCHAR(20)		NULL,
	FLD_QUIZ2		VARCHAR(20)		NULL,
	FLD_ANSWER2		VARCHAR(20)		NULL
);

CREATE TABLE TBL_CHARACTER
(
	FLD_LOGINID		CHAR(10)		NOT NULL,
	FLD_CHARNAME		CHAR(20)		NOT NULL,

	FLD_JOB			CHAR(1)			NOT NULL,
	FLD_GENDER		CHAR(1)			NOT NULL,

	FLD_LEVEL		TINYINT			NOT NULL,
	
	FLD_DIRECTION		INT			NOT NULL,
	FLD_CX			INT			NOT NULL,
	FLD_CY			INT			NOT NULL,
	FLD_MAPNAME		CHAR(16)		NOT NULL,
	
	FLD_GOLD		INT			NOT NULL,
	
	FLD_DRESS_ID		CHAR(11)		NOT NULL,
	FLD_WEAPON_ID		CHAR(11)		NOT NULL,
	FLD_LEFTHAND_ID		CHAR(11)		NOT NULL,
	FLD_RIGHTHAND_ID	CHAR(11)		NOT NULL,
	FLD_HELMET_ID		CHAR(11)		NOT NULL,
	FLD_NECKLACE_ID		CHAR(11)		NOT NULL,
	FLD_ARMRINGL_ID		CHAR(11)		NOT NULL,
	FLD_ARMRINGR_ID		CHAR(11)		NOT NULL,
	FLD_RINGL_ID		CHAR(11)		NOT NULL,
	FLD_RINGR_ID		CHAR(11)		NOT NULL
);

CREATE TABLE TBL_CHARACTER_ITEM
(
	FLD_LOGINID		CHAR(10)		NOT NULL,
	FLD_CHARNAME		CHAR(20)		NOT NULL,

	FLD_ITEM1		CHAR(12)		NULL,
	FLD_ITEM2		CHAR(12)		NULL,
	FLD_ITEM3		CHAR(12)		NULL,
	FLD_ITEM4		CHAR(12)		NULL,
	FLD_ITEM5		CHAR(12)		NULL,
	FLD_ITEM6		CHAR(12)		NULL,
	FLD_ITEM7		CHAR(12)		NULL,
	FLD_ITEM8		CHAR(12)		NULL,
	FLD_ITEM9		CHAR(12)		NULL,
	FLD_ITEM10		CHAR(12)		NULL,
	FLD_ITEM11		CHAR(12)		NULL,
	FLD_ITEM12		CHAR(12)		NULL,
	FLD_ITEM13		CHAR(12)		NULL,
	FLD_ITEM14		CHAR(12)		NULL,
	FLD_ITEM15		CHAR(12)		NULL,
	FLD_ITEM16		CHAR(12)		NULL,
	FLD_ITEM17		CHAR(12)		NULL,
	FLD_ITEM18		CHAR(12)		NULL,
	FLD_ITEM19		CHAR(12)		NULL,
	FLD_ITEM20		CHAR(12)		NULL,
	FLD_ITEM21		CHAR(12)		NULL,
	FLD_ITEM22		CHAR(12)		NULL,
	FLD_ITEM23		CHAR(12)		NULL,
	FLD_ITEM24		CHAR(12)		NULL,
	FLD_ITEM25		CHAR(12)		NULL,
	FLD_ITEM26		CHAR(12)		NULL,
	FLD_ITEM27		CHAR(12)		NULL,
	FLD_ITEM28		CHAR(12)		NULL,
	FLD_ITEM29		CHAR(12)		NULL,
	FLD_ITEM30		CHAR(12)		NULL,
	FLD_ITEM31		CHAR(12)		NULL,
	FLD_ITEM32		CHAR(12)		NULL,
	FLD_ITEM33		CHAR(12)		NULL,
	FLD_ITEM34		CHAR(12)		NULL,
	FLD_ITEM35		CHAR(12)		NULL,
	FLD_ITEM36		CHAR(12)		NULL,
	FLD_ITEM37		CHAR(12)		NULL,
	FLD_ITEM38		CHAR(12)		NULL,
	FLD_ITEM39		CHAR(12)		NULL,
	FLD_ITEM40		CHAR(12)		NULL,
	FLD_ITEM41		CHAR(12)		NULL,
	FLD_ITEM42		CHAR(12)		NULL,
	FLD_ITEM43		CHAR(12)		NULL,
	FLD_ITEM44		CHAR(12)		NULL,
	FLD_ITEM45		CHAR(12)		NULL,
	FLD_ITEM46		CHAR(12)		NULL,
	FLD_ITEM47		CHAR(12)		NULL,
	FLD_ITEM48		CHAR(12)		NULL,
	FLD_ITEM49		CHAR(12)		NULL,
	FLD_ITEM50		CHAR(12)		NULL,
	FLD_ITEM51		CHAR(12)		NULL,
	FLD_ITEM52		CHAR(12)		NULL,
	FLD_ITEM53		CHAR(12)		NULL,
	FLD_ITEM54		CHAR(12)		NULL,
	FLD_ITEM55		CHAR(12)		NULL,
	FLD_ITEM56		CHAR(12)		NULL,
	FLD_ITEM57		CHAR(12)		NULL,
	FLD_ITEM58		CHAR(12)		NULL,
	FLD_ITEM59		CHAR(12)		NULL,
	FLD_ITEM60		CHAR(12)		NULL,
	FLD_ITEM61		CHAR(12)		NULL,
	FLD_ITEM62		CHAR(12)		NULL,
	FLD_ITEM63		CHAR(12)		NULL,
	FLD_ITEM64		CHAR(12)		NULL,
	FLD_ITEM65		CHAR(12)		NULL,
	FLD_ITEM66		CHAR(12)		NULL
);

CREATE TABLE TBL_CHARACTER_MAGIC
(
	FLD_LOGINID		CHAR(10)		NOT NULL,
	FLD_CHARNAME		CHAR(20)		NOT NULL,

	FLD_LEVEL0		TINYINT			DEFAULT 0,
	FLD_USEKEY0		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN0		INT			DEFAULT 0,

	FLD_LEVEL1		TINYINT			DEFAULT 0,
	FLD_USEKEY1		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN1		INT			DEFAULT 0,

	FLD_LEVEL2		TINYINT			DEFAULT 0,
	FLD_USEKEY2		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN2		INT			DEFAULT 0,

	FLD_LEVEL3		TINYINT			DEFAULT 0,
	FLD_USEKEY3		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN3		INT			DEFAULT 0,

	FLD_LEVEL4		TINYINT			DEFAULT 0,
	FLD_USEKEY4		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN4		INT			DEFAULT 0,

	FLD_LEVEL5		TINYINT			DEFAULT 0,
	FLD_USEKEY5		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN5		INT			DEFAULT 0,

	FLD_LEVEL6		TINYINT			DEFAULT 0,
	FLD_USEKEY6		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN6		INT			DEFAULT 0,

	FLD_LEVEL7		TINYINT			DEFAULT 0,
	FLD_USEKEY7		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN7		INT			DEFAULT 0,

	FLD_LEVEL8		TINYINT			DEFAULT 0,
	FLD_USEKEY8		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN8		INT			DEFAULT 0,

	FLD_LEVEL9		TINYINT			DEFAULT 0,
	FLD_USEKEY9		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN9		INT			DEFAULT 0,

	FLD_LEVEL10		TINYINT			DEFAULT 0,
	FLD_USEKEY10		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN10		INT			DEFAULT 0,

	FLD_LEVEL11		TINYINT			DEFAULT 0,
	FLD_USEKEY11		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN11		INT			DEFAULT 0,

	FLD_LEVEL12		TINYINT			DEFAULT 0,
	FLD_USEKEY12		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN12		INT			DEFAULT 0,

	FLD_LEVEL13		TINYINT			DEFAULT 0,
	FLD_USEKEY13		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN13		INT			DEFAULT 0,

	FLD_LEVEL14		TINYINT			DEFAULT 0,
	FLD_USEKEY14		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN14		INT			DEFAULT 0,

	FLD_LEVEL15		TINYINT			DEFAULT 0,
	FLD_USEKEY15		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN15		INT			DEFAULT 0,

	FLD_LEVEL16		TINYINT			DEFAULT 0,
	FLD_USEKEY16		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN16		INT			DEFAULT 0,

	FLD_LEVEL17		TINYINT			DEFAULT 0,
	FLD_USEKEY17		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN17		INT			DEFAULT 0,

	FLD_LEVEL18		TINYINT			DEFAULT 0,
	FLD_USEKEY18		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN18		INT			DEFAULT 0,

	FLD_LEVEL19		TINYINT			DEFAULT 0,
	FLD_USEKEY19		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN19		INT			DEFAULT 0,

	FLD_LEVEL20		TINYINT			DEFAULT 0,
	FLD_USEKEY20		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN20		INT			DEFAULT 0,

	FLD_LEVEL21		TINYINT			DEFAULT 0,
	FLD_USEKEY21		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN21		INT			DEFAULT 0,

	FLD_LEVEL22		TINYINT			DEFAULT 0,
	FLD_USEKEY22		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN22		INT			DEFAULT 0,

	FLD_LEVEL23		TINYINT			DEFAULT 0,
	FLD_USEKEY23		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN23		INT			DEFAULT 0,

	FLD_LEVEL24		TINYINT			DEFAULT 0,
	FLD_USEKEY24		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN24		INT			DEFAULT 0,

	FLD_LEVEL25		TINYINT			DEFAULT 0,
	FLD_USEKEY25		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN25		INT			DEFAULT 0,

	FLD_LEVEL26		TINYINT			DEFAULT 0,
	FLD_USEKEY26		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN26		INT			DEFAULT 0,

	FLD_LEVEL27		TINYINT			DEFAULT 0,
	FLD_USEKEY27		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN27		INT			DEFAULT 0,

	FLD_LEVEL28		TINYINT			DEFAULT 0,
	FLD_USEKEY28		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN28		INT			DEFAULT 0,

	FLD_LEVEL29		TINYINT			DEFAULT 0,
	FLD_USEKEY29		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN29		INT			DEFAULT 0,

	FLD_LEVEL30		TINYINT			DEFAULT 0,
	FLD_USEKEY30		TINYINT			DEFAULT 0,
	FLD_CURRTRAIN30		INT			DEFAULT 0

);

CREATE TABLE TBL_GUARD
(
	FLD_INDEX		INT			NOT NULL,
	FLD_ID			CHAR(14)		NOT NULL,
	FLD_MAPNAME		CHAR(14)		NOT NULL,
	FLD_POSX		INT			NOT NULL,
	FLD_POSY		INT			NOT NULL,
	FLD_DIRECTION		SMALLINT		NOT NULL,
	FLD_DESCRIPTION		VARCHAR(100)		NULL
);

CREATE TABLE TBL_HORSE
(
	FLD_CHARNAME		CHAR(20)		NOT NULL,
	FLD_HORSEINDEX		CHAR(11)		NOT NULL,

	FLD_HORSETYPE		TINYINT			NOT NULL,

	FLD_LEVEL		TINYINT			NULL,
	FLD_PRICE		INT			NULL,
	FLD_HP			TINYINT			NULL
);

CREATE TABLE TBL_MAGIC
(
	FLD_INDEX		INT			NOT NULL,
	FLD_NAME		CHAR(12)		NOT NULL,
	FLD_EFFECTTYPE		SMALLINT		NULL,
	FLD_EFFECT		SMALLINT		NULL,
	FLD_SPELL		SMALLINT		NULL,
	FLD_POWER		SMALLINT		NULL,
	FLD_MAXPOWER		SMALLINT		NULL,
	FLD_DEFSPELL		SMALLINT		NULL,
	FLD_DEFPOWER		SMALLINT		NULL,
	FLD_DEFMAXPOWER		SMALLINT		NULL,
	FLD_JOB			SMALLINT		NULL,
	FLD_NEEDL1		SMALLINT		NULL,
	FLD_L1TRAIN		INT			NULL,
	FLD_NEEDL2		SMALLINT		NULL,
	FLD_L2TRAIN		INT			NULL,
	FLD_NEEDL3		SMALLINT		NULL,
	FLD_L3TRAIN		INT			NULL,
	FLD_DELAY		SMALLINT		NULL,
	FLD_DESC		CHAR(8)			NULL,
	FLD_DESCRIPTION		VARCHAR(100)		NULL
);

CREATE TABLE TBL_MAPINFO
(
	FLD_MAPFILENAME		CHAR(14)		NOT NULL,
	FLD_MAPNAME		VARCHAR(40)		NOT NULL,
	FLD_SERVERINDEX		SMALLINT		NOT NULL,
	FLD_ATTRIBUTE		INT			NULL,
	FLD_RECALLMAPFNAME	CHAR(14)		NULL,
	FLD_DESCRIPTION		VARCHAR(100)		NULL
);

CREATE TABLE TBL_MERCHANT
(
	FLD_ID			INT			AUTO_INCREMENT PRIMARY KEY,
	FLD_MAPNAME		CHAR(14)		NOT NULL,
	FLD_POSX		INT			NOT NULL,
	FLD_POSY		INT			NOT NULL,
	FLD_NPCNAME		VARCHAR(40)		NOT NULL,
	FLD_FACE		INT			NOT NULL,
	FLD_BODY		INT			NOT NULL,
	FLD_GENDER		SMALLINT		NOT NULL,
	FLD_DESCRIPTION		VARCHAR(100)		NULL
);

CREATE TABLE TBL_MONGEN
(
	FLD_INDEX		INT			NOT NULL,
	FLD_MAPNAME		CHAR(14)		NOT NULL,
	FLD_X			INT			NOT NULL,
	FLD_Y			INT			NULL,
	FLD_MONNAME		CHAR(14)		NULL,
	FLD_AREA		SMALLINT		NULL,
	FLD_COUNT		SMALLINT		NULL,
	FLD_GENTIME		INT			NULL,
	FLD_SMALLGENRATE	INT			NULL,
	FLD_DESCRIPTION		VARCHAR(100)		NULL
);

CREATE TABLE TBL_MONSTER
(
	FLD_NAME		CHAR(14)		NOT NULL,
	FLD_RACE		SMALLINT		NULL,
	FLD_RACEIMG		SMALLINT		NULL,
	FLD_APPR		SMALLINT		NULL,
	FLD_LEVEL		SMALLINT		NULL,
	FLD_UNDEAD		SMALLINT		NULL,
	FLD_EXP			SMALLINT		NULL,
	FLD_HP			SMALLINT		NULL,
	FLD_MP			SMALLINT		NULL,
	FLD_AC			SMALLINT		NULL,
	FLD_MAXAC		SMALLINT		NULL,
	FLD_MAC			SMALLINT		NULL,
	FLD_MAXMAC		SMALLINT		NULL,
	FLD_DC			SMALLINT		NULL,
	FLD_MAXDC		SMALLINT		NULL,
	FLD_SPEED		SMALLINT		NULL,
	FLD_HIT			SMALLINT		NULL,
	FLD_WALKSPEED		SMALLINT		NULL,
	FLD_ATTACKSPEED		SMALLINT		NULL
);

CREATE TABLE TBL_MOVEMAPEVENT
(
	FLD_INDEX		INT			NOT NULL,
	FLD_SMAPFILENAME	CHAR(14)		NOT NULL,
	FLD_SX			INT			NOT NULL,
	FLD_SY			INT			NOT NULL,
	FLD_DMAPFILENAME	CHAR(14)		NOT NULL,
	FLD_DX			INT			NOT NULL,
	FLD_DY			INT			NOT NULL,
	FLD_DESCRIPTION		VARCHAR(100)		NULL
);

CREATE TABLE TBL_NPC
(
	FLD_INDEX		INT			NOT NULL,
	FLD_NAME		CHAR(14)		NOT NULL,
	FLD_RACE		SMALLINT		NOT NULL,
	FLD_MAPNAME		CHAR(14)		NOT NULL,
	FLD_POSX		INT			NOT NULL,
	FLD_POSY		INT			NOT NULL,
	FLD_FACE		SMALLINT		NOT NULL,
	FLD_BODY		SMALLINT		NOT NULL,
	FLD_DESCRIPTION		VARCHAR(100)		NULL
);

CREATE TABLE TBL_SERVERINFO
(
	FLD_SERVERIDX		INT		AUTO_INCREMENT PRIMARY KEY,
	FLD_SERVERNAME		NCHAR(40)	NOT NULL,
	FLD_SERVERIP		NCHAR(20)	NOT NULL
);

CREATE TABLE TBL_STARTPOINT
(
	FLD_INDEX		INT			NOT NULL,
	FLD_MAPNAME		CHAR(14)		NOT NULL,
	FLD_POSX		INT			NOT NULL,
	FLD_POSY		INT			NOT NULL,
	FLD_DESCRIPTION		VARCHAR(100)		NULL
);

CREATE TABLE TBL_STDITEM
(
	FLD_INDEX		INT			AUTO_INCREMENT PRIMARY KEY,
	FLD_NAME		VARCHAR(20)		NOT NULL,
	FLD_STDMODE		SMALLINT		NULL,			
	FLD_SHAPE		SMALLINT		NULL,
	FLD_WEIGHT		SMALLINT		NULL,
	FLD_ANICOUNT		SMALLINT		NULL,
	FLD_SOURCE		SMALLINT		NULL,
	FLD_LOOKS		INT			NULL,
	FLD_DURAMAX		INT			NULL,
	FLD_AC			SMALLINT		NULL,
	FLD_AC2			SMALLINT		NULL,
	FLD_MAC			SMALLINT		NULL,
	FLD_MAC2		SMALLINT		NULL,
	FLD_DC			SMALLINT		NULL,
	FLD_DC2			SMALLINT		NULL,
	FLD_MC			SMALLINT		NULL,
	FLD_MC2			SMALLINT		NULL,
	FLD_SC			SMALLINT		NULL,
	FLD_SC2			SMALLINT		NULL,
	FLD_NEED		SMALLINT		NULL,
	FLD_NEEDLEVEL		SMALLINT		NULL,
	FLD_PRICE		INT			NULL,
	FLD_STOCK		INT			NULL
);

CREATE TABLE TBL_STDITEM_ACCESSORY
(
	FLD_INDEX		INT			NOT NULL,
	FLD_NAME		VARCHAR(20)		NOT NULL,
	FLD_STDMODE		SMALLINT		NULL,			
	FLD_SHAPE		SMALLINT		NULL,
	FLD_WEIGHT		SMALLINT		NULL,
	FLD_ANICOUNT		SMALLINT		NULL,
	FLD_SOURCE		SMALLINT		NULL,
	FLD_LOOKS		INT			NULL,
	FLD_DURAMAX		INT			NULL,
	FLD_AC			SMALLINT		NULL,
	FLD_AC2			SMALLINT		NULL,
	FLD_MAC			SMALLINT		NULL,
	FLD_MAC2		SMALLINT		NULL,
	FLD_DC			SMALLINT		NULL,
	FLD_DC2			SMALLINT		NULL,
	FLD_MC			SMALLINT		NULL,
	FLD_MC2		SMALLINT		NULL,
	FLD_SC			SMALLINT		NULL,
	FLD_SC2			SMALLINT		NULL,
	FLD_NEED		SMALLINT		NULL,
	FLD_NEEDLEVEL		SMALLINT		NULL,
	FLD_PRICE		INT			NULL,
	FLD_STOCK		INT			NULL
);

CREATE TABLE TBL_STDITEM_ETC
(
	FLD_INDEX		INT			NOT NULL,
	FLD_NAME		VARCHAR(20)		NOT NULL,
	FLD_STDMODE		SMALLINT		NULL,			
	FLD_SHAPE		SMALLINT		NULL,
	FLD_LOOKS		INT			NULL,
	FLD_WEIGHT		SMALLINT		NULL,
	FLD_PRICE		INT			NULL,
	FLD_VAL1		INT			NULL,
	FLD_VAL2		INT			NULL
);

CREATE TABLE TBL_STDITEMARMOR
(
	FLD_INDEX		INT			AUTO_INCREMENT PRIMARY KEY,
	FLD_NAME		VARCHAR(20)		NOT NULL,
	FLD_STDMODE		SMALLINT		NULL,			
	FLD_SHAPE		SMALLINT		NULL,
	FLD_WEIGHT		SMALLINT		NULL,
	FLD_ANICOUNT		SMALLINT		NULL,
	FLD_SOURCE		SMALLINT		NULL,
	FLD_LOOKS		INT			NULL,
	FLD_DURAMAX		INT			NULL,
	FLD_AC			SMALLINT		NULL,
	FLD_AC2			SMALLINT		NULL,
	FLD_MAC			SMALLINT		NULL,
	FLD_MAC2		SMALLINT		NULL,
	FLD_DC			SMALLINT		NULL,
	FLD_DC2			SMALLINT		NULL,
	FLD_MC			SMALLINT		NULL,
	FLD_MC2			SMALLINT		NULL,
	FLD_SC			SMALLINT		NULL,
	FLD_SC2			SMALLINT		NULL,
	FLD_NEED		SMALLINT		NULL,
	FLD_NEEDLEVEL		SMALLINT		NULL,
	FLD_PRICE		INT			NULL,
	FLD_STOCK		INT			NULL
);

CREATE TABLE TBL_STDITEMWEAPON
(
	FLD_INDEX		INT			AUTO_INCREMENT PRIMARY KEY,
	FLD_NAME		VARCHAR(20)		NOT NULL,
	FLD_STDMODE		SMALLINT		NULL,			
	FLD_SHAPE		SMALLINT		NULL,
	FLD_WEIGHT		SMALLINT		NULL,
	FLD_ANICOUNT		SMALLINT		NULL,
	FLD_SOURCE		SMALLINT		NULL,
	FLD_LOOKS		INT			NULL,
	FLD_DURAMAX		INT			NULL,
	FLD_AC			SMALLINT		NULL,
	FLD_AC2			SMALLINT		NULL,
	FLD_MAC			SMALLINT		NULL,
	FLD_MAC2		SMALLINT		NULL,
	FLD_DC			SMALLINT		NULL,
	FLD_DC2			SMALLINT		NULL,
	FLD_MC			SMALLINT		NULL,
	FLD_MC2			SMALLINT		NULL,
	FLD_SC			SMALLINT		NULL,
	FLD_SC2			SMALLINT		NULL,
	FLD_NEED		SMALLINT		NULL,
	FLD_NEEDLEVEL		SMALLINT		NULL,
	FLD_PRICE		INT			NULL,
	FLD_STOCK		INT			NULL
);

CREATE TABLE TBL_USERITEM
(
	FLD_CHARNAME		NCHAR(20)		NOT NULL,
	FLD_STDTYPE		NCHAR(1)		NOT NULL,
	FLD_MAKEDATE		NCHAR(6)		NOT NULL,
	FLD_MAKEINDEX		NCHAR(5)		NOT NULL,
	FLD_STDINDEX		INT			NOT NULL,
	FLD_DURA		INT			NOT NULL,
	FLD_DURAMAX		INT			NOT NULL,
	FLD_VALUE1		TINYINT			NOT NULL,
	FLD_VALUE2		TINYINT			NOT NULL,
	FLD_VALUE3		TINYINT			NOT NULL,
	FLD_VALUE4		TINYINT			NOT NULL,
	FLD_VALUE5		TINYINT			NOT NULL,
	FLD_VALUE6		TINYINT			NOT NULL,
	FLD_VALUE7		TINYINT			NOT NULL,
	FLD_VALUE8		TINYINT			NOT NULL,
	FLD_VALUE9		TINYINT			NOT NULL,
	FLD_VALUE10		TINYINT			NOT NULL,
	FLD_VALUE11		TINYINT			NOT NULL,
	FLD_VALUE12		TINYINT			NOT NULL,
	FLD_VALUE13		TINYINT			NOT NULL,
	FLD_VALUE14		TINYINT			NOT NULL
);


/*fire 2014-08-15 传奇3 mysql数据库 建表脚本*/